In [1]:
from utils.dataset import Return_Question_tensor
from utils.model import GPT
from utils.config import GPTConfig
import torch

In [2]:
config = GPTConfig()

model = GPT(config)  # 你的模型定义
model.to('cuda')
# 加载 checkpoint
checkpoint_path = 'checkpoints/model_epoch_1.pt'  # 替换为你要加载的 checkpoint 路径
checkpoint = torch.load(checkpoint_path)

# 恢复模型的状态
model.load_state_dict(checkpoint['model_state_dict'])

# 将模型设置为评估模式（如果你只是进行推理）
model.eval()
# 或者设置为训练模式（如果你要继续训练）
# model.train()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_31032\4250048475.py:7: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path)


GPT(
  (token_embedding): Embedding(50257, 256)
  (position_embedding): Embedding(512, 256)
  (blocks): Sequential(
    (0): Block(
      (layernorm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (layernorm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (atten): GroupQueryAttention(
        (w_q): Linear(in_features=256, out_features=256, bias=True)
        (w_k): Linear(in_features=256, out_features=64, bias=True)
        (w_v): Linear(in_features=256, out_features=64, bias=True)
        (w_o): Linear(in_features=256, out_features=256, bias=True)
        (softmax): Softmax(dim=-1)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ffn): FFN(
        (ffn): Sequential(
          (0): Linear(in_features=256, out_features=1024, bias=True)
          (1): GELU(approximate='none')
          (2): Linear(in_features=1024, out_features=256, bias=True)
          (3): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (1): Block(
      (layerno

In [3]:
import tiktoken
enc = tiktoken.get_encoding("gpt2")

In [7]:
x = Return_Question_tensor("你叫什么？",config).to("cuda")
out = model.generate(x)

tensor([[8129]], device='cuda:0')
tensor([[3150]], device='cuda:0')
tensor([[21638]], device='cuda:0')
tensor([[33461]], device='cuda:0')
tensor([[14661]], device='cuda:0')
tensor([[50256]], device='cuda:0')


In [8]:
enc.decode(x.data.to("cpu").numpy()[0])

'你叫什么？<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endo

In [9]:
enc.decode(out.data.to("cpu").numpy()[0])

'你叫什么？<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endo

In [10]:
x.shape

torch.Size([1, 512])

In [11]:
out.shape

torch.Size([1, 518])

In [16]:
print(out[:,512:])
print(out[:,512:].shape)

tensor([[ 8129,  3150, 21638, 33461, 14661, 50256]], device='cuda:0')
torch.Size([1, 6])


In [22]:
enc.decode(out[:,config.max_length:].data.to("cpu").numpy()[0])

' Professoromswo Allison AV<|endoftext|>'